# tasks file for roles/general-config
---

#- name: ---  graylog installation ---
- include_tasks: java.yml
- include_tasks: elasticsearch.yml
- include_tasks: mongodb.yml
- include_tasks: graylog.yml
